// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BFBtn: typeof import('./components/button/BFBtn.vue')['default']
    CardRow: typeof import('./components/layout/CardRow.vue')['default']
    Col: typeof import('./components/layout/Col.vue')['default']
    CommonCard: typeof import('./components/CommonCard.vue')['default']
    ControlCenterToggle: typeof import('./components/toggle/ControlCenterToggle.vue')['default']
    DrawerToggle: typeof import('./components/toggle/DrawerToggle.vue')['default']
    Heading: typeof import('./components/Heading.vue')['default']
    Headline: typeof import('./components/Headline.vue')['default']
    Item: typeof import('./components/list/Item.vue')['default']
    List: typeof import('./components/list/List.vue')['default']
    LottieIcon: typeof import('./components/LottieIcon.vue')['default']
    Menu: typeof import('./components/menu/Menu.vue')['default']
    ReloadBtn: typeof import('./components/button/ReloadBtn.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./components/menu/Select.vue')['default']
    SwitchCard: typeof import('./components/SwitchCard.vue')['default']
    ThemeToggle: typeof import('./components/toggle/ThemeToggle.vue')['default']
    Title: typeof import('./components/Title.vue')['default']
    VSquareBtn: typeof import('./components/button/VSquareBtn.vue')['default']
    Wave: typeof import('./components/Wave.vue')['default']
    WindowControl: typeof import('./components/layout/WindowControl.vue')['default']
  }
}

export {}
